### ISSUE TITLE
Fix typo in readme file

### ISSUE THREAD

**Issue by fabiopacifici** [fabiopacificicom/social-login-for-laravel#1]
https://github.com/fabiopacificicom/social-login-for-laravel/blob/9e35effd1c23117e5740e2bc984ca41a7f30ed54/README.md?plain=1#L45

**Comment by claireoe** [comment]
@fabiopacifici Please I would like to work on this issue.

**Comment by claireoe** [comment]
thanks! 
I'll create a pull request for this

**Comment by claireoe** [comment]
@fabiopacifici I dont have permissions to commit changes

**Comment by fabiopacifici** [comment]
Hi cloe, I reviewed your PR and merged. Thanks for your help
