### ISSUE TITLE
Fix incorrect package name

### ISSUE THREAD

**Issue by fabiopacifici** [fabiopacificicom/social-login-for-laravel#3]
Update the readme file, an incorrect package name is used in the documented installation steps.

Change from 
`composer require pacificdev/social-login`
To:
`composer require pacificdev/social-login-for-laravel`

https://github.com/fabiopacificicom/social-login-for-laravel/blob/9e35effd1c23117e5740e2bc984ca41a7f30ed54/README.md?plain=1#L27

**Comment by claireoe** [comment]
@fabiopacifici please I would like to work on this
